services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=GapSense@2026
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./backend/src
      dockerfile: GapSense.API/Dockerfile
    ports:
      - "5172:5172"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GapSenseDB;User Id=sa;Password=GapSense@2026;TrustServerCertificate=True
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/gapsense-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/gapsense-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data:
