// <auto-generated />
using System;
using GapSense.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GapSense.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GapSenseDbContext))]
    [Migration("20260406072242_AddLecturerSecuritySettings")]
    partial class AddLecturerSecuritySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerAcademicSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AssignedFaculty")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultModule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LecturerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerProfileId")
                        .IsUnique();

                    b.ToTable("LecturerAcademicSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000002"),
                            AcademicYear = "2025/2026",
                            AssignedFaculty = "Faculty of Computing — Software Engineering",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModule = "INTE 3123 — Data Structures & Algorithms",
                            IsActive = true,
                            LecturerProfileId = new Guid("00000000-0000-4000-8000-000000000001"),
                            Semester = "Semester 1"
                        });
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AssignmentReminders")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LecturerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("StudentRiskAlerts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WeeklyReports")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LecturerProfileId")
                        .IsUnique();

                    b.ToTable("LecturerNotificationSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000003"),
                            AssignmentReminders = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAlerts = true,
                            IsActive = true,
                            LecturerProfileId = new Guid("00000000-0000-4000-8000-000000000001"),
                            StudentRiskAlerts = true,
                            WeeklyReports = true
                        });
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LecturerProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Faculty of Computing",
                            Email = "nimal.perera@sliit.lk",
                            FullName = "Dr. Nimal Perera",
                            IsActive = true,
                            PhoneNumber = "+94 77 123 4567"
                        });
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerSecuritySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogoutAllDevicesUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LecturerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerProfileId")
                        .IsUnique();

                    b.ToTable("LecturerSecuritySettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LecturerProfileId = new Guid("00000000-0000-4000-8000-000000000001"),
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("GapSense.Domain.Entities.ReadinessResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("ReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCode");

                    b.HasIndex("StudentId");

                    b.HasIndex("Batch", "Semester");

                    b.ToTable("ReadinessResults", (string)null);
                });

            modelBuilder.Entity("GapSense.Domain.Entities.RecommendationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RiskLevel", "ResourceType");

                    b.ToTable("RecommendationRules", (string)null);
                });

            modelBuilder.Entity("GapSense.Domain.Entities.RiskThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HighRiskBelowPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MediumRiskBelowPercent")
                        .HasColumnType("int");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCode", "Batch", "Semester")
                        .IsUnique();

                    b.ToTable("RiskThresholds", (string)null);
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerAcademicSettings", b =>
                {
                    b.HasOne("GapSense.Domain.Entities.LecturerProfile", "LecturerProfile")
                        .WithOne("AcademicSettings")
                        .HasForeignKey("GapSense.Domain.Entities.LecturerAcademicSettings", "LecturerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LecturerProfile");
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerNotificationSettings", b =>
                {
                    b.HasOne("GapSense.Domain.Entities.LecturerProfile", "LecturerProfile")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("GapSense.Domain.Entities.LecturerNotificationSettings", "LecturerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LecturerProfile");
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerSecuritySettings", b =>
                {
                    b.HasOne("GapSense.Domain.Entities.LecturerProfile", "LecturerProfile")
                        .WithOne("SecuritySettings")
                        .HasForeignKey("GapSense.Domain.Entities.LecturerSecuritySettings", "LecturerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LecturerProfile");
                });

            modelBuilder.Entity("GapSense.Domain.Entities.LecturerProfile", b =>
                {
                    b.Navigation("AcademicSettings");

                    b.Navigation("NotificationSettings");

                    b.Navigation("SecuritySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
