/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'on-error-container': '#93000a',
        'on-primary-container': '#bbd0ff',
        'on-tertiary-container': '#a0d7ff',
        'error-container': '#ffdad6',
        'primary-fixed': '#d7e2ff',
        'inverse-surface': '#2d3133',
        'secondary-fixed': '#d5e3fc',
        'primary-fixed-dim': '#acc7ff',
        'on-background': '#191c1e',
        'on-primary-fixed': '#001a40',
        'on-primary-fixed-variant': '#004491',
        'inverse-primary': '#acc7ff',
        'primary-container': '#0056b3',
        outline: '#727784',
        'on-error': '#ffffff',
        tertiary: '#004666',
        'on-secondary-fixed': '#0d1c2e',
        'secondary-container': '#d5e3fc',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'on-surface': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#424752',
        'tertiary-container': '#005f89',
        'surface-container-highest': '#e0e3e5',
        secondary: '#515f74',
        primary: '#003f87',
        surface: '#f7f9fb',
        'outline-variant': '#c2c6d4',
        'on-secondary-container': '#57657a',
        background: '#f7f9fb',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#b9c7df',
        'tertiary-fixed': '#c9e6ff',
        'on-tertiary-fixed-variant': '#004c6e',
        'on-secondary-fixed-variant': '#3a485b',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#89ceff',
        'on-secondary-fixed': '#0d1c2e',
        'on-tertiary-fixed': '#001e2f',
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-tertiary': '#ffffff',
        'surface-tint': '#115cb9',
        'on-tertiary-fixed': '#001e2f',
        // Aliases used by your pasted HTML
        'primary-fixed-variant': '#bbd0ff',
      },
      fontFamily: {
        headline: ['Manrope', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'ui-sans-serif', 'system-ui'],
        label: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

