// <auto-generated />
using System;
using GapSense.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GapSense.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429120000_AddOptionalProductModules")]
    public partial class AddOptionalProductModules
    {
        // This lightweight designer exists only so EF recognizes the migration in the chain.
        // The full target model is not required for applying migrations.
    }
}

