using System.Text.Json;
using GapSense.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace GapSense.Application.Pdf;

public static class ReadinessResultPdfGenerator
{
    private sealed record TopicRow(string TopicName, int Percent);

    static ReadinessResultPdfGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Generate(ReadinessResult r)
    {
        var topics = ParseTopics(r.TopicPerformanceJson);

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(header =>
                {
                    header.Item().Text("SLIIT GapSense").FontSize(10).FontColor(Colors.Blue.Medium);
                    header.Item().PaddingTop(4).Text("Readiness Result Report").FontSize(20).Bold();
                    header.Item().PaddingTop(2).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Text("Student information").FontSize(14).Bold();
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(3);
                        });
                        Row(table, "Name", r.StudentName);
                        Row(table, "Student ID", r.StudentId);
                        Row(table, "Module", r.ModuleCode);
                        Row(table, "Semester", r.SemesterLabel);
                        Row(table, "Attempt #", r.AttemptLabel);
                        Row(table, "Analysis date", r.AnalysisDateLabel);
                    });

                    col.Item().PaddingTop(8).Text("Summary").FontSize(14).Bold();
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c => { c.RelativeColumn(2); c.RelativeColumn(3); });
                        Row(table, "Total score", $"{r.TotalScorePercent}%");
                        Row(table, "Risk assessment", $"{FormatRisk(r.RiskLevel)} — {r.RiskDescription}");
                        Row(table, "Weak topics (count)", r.WeakTopicsCount.ToString());
                        Row(table, "Weak topics (severity)", $"{r.WeakTopicsSeverityLabel}; {r.WeakTopicsHelperText}");
                        Row(table, "Action plan (recommendations)", r.ActionPlanRecommendationCount.ToString());
                        Row(table, "Action plan (label)", $"{r.ActionPlanBadgeLabel}; {r.ActionPlanHelperText}");
                    });

                    col.Item().PaddingTop(8).Text("Interpretation").FontSize(14).Bold();
                    col.Item().Text(r.InterpretationMessage).Italic();

                    col.Item().PaddingTop(8).Text("Topic performance").FontSize(14).Bold();
                    if (topics.Count == 0)
                    {
                        col.Item().Text("No topic breakdown available.");
                    }
                    else
                    {
                        foreach (var t in topics)
                        {
                            col.Item().Text($"{t.TopicName}: {t.Percent}%");
                        }
                    }

                    col.Item().PaddingTop(24).AlignRight().Text(text =>
                    {
                        text.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Grey.Medium));
                        text.Span("Generated by GapSense — ");
                        text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + " UTC");
                    });
                });
            });
        }).GeneratePdf();
    }

    private static void Row(QuestPDF.Fluent.TableDescriptor table, string label, string value)
    {
        table.Cell().PaddingVertical(4).Text(label).FontColor(Colors.Grey.Darken2);
        table.Cell().PaddingVertical(4).Text(value);
    }

    private static string FormatRisk(string level)
    {
        return level.ToLowerInvariant() switch
        {
            "high" => "High risk",
            "medium" => "Medium risk",
            "low" => "Low risk",
            _ => level,
        };
    }

    private static IReadOnlyList<TopicRow> ParseTopics(string json)
    {
        if (string.IsNullOrWhiteSpace(json)) return Array.Empty<TopicRow>();
        try
        {
            var rows = JsonSerializer.Deserialize<List<TopicRow>>(json);
            return rows ?? new List<TopicRow>();
        }
        catch
        {
            return Array.Empty<TopicRow>();
        }
    }
}
